export const SORTING_ORDER_NEW = 'new'
export const SORTING_ORDER_OLD = 'old'
export const STATUS_PENDING = 'pending'
export const STATUS_ACTIVE = 'active'
export const STATUS_VERIFIED = 'verified'
export const STATUS_REJECTED = 'rejected'
export const STATUS_PAYMENT_PENDING = 'pending'
export const STATUS_PAYMENT_COMPLETED = 'completed'
