export const SORTING_ORDER_NEW = 'new'
export const SORTING_ORDER_OLD = 'old'
export const STATUS_PENDING = 'pending'
export const STATUS_ACTIVE = 'active'
export const STATUS_VERIFIED = 'verified'
export const STATUS_REJECTED = 'rejected'
export const STATUS_PAYMENT_PENDING = 'pending'
export const STATUS_PAYMENT_COMPLETED = 'completed'
export const ROLE_USER = 'user'
export const ROLE_PROVIDER = 'provider'
export const ROLE_ADMIN = 'admin'
export const DEFAULT_IMAGE_SOURCE = 'https://res.cloudinary.com'

export const SEARCH_TYPE_PROVIDER = 'provider'
export const SEARCH_TYPE_SUBCATEGORY = 'subcategory'
export const CATEGORY_HOTEL_SLUG = 'hotel'
export const CATEGORY_LEISURE_SLUG = 'leisure'
export const CATEGORY_SHOPPING_SLUG = 'shopping'
