import type {Metadata} from "next";
// import localFont from "next/font/local";
// import '../../../src/i18n';
import "./globals.css";
import Header from "@/components/Header";
import React from "react";
import {createClient} from '@/utils/supabase/server'
import {cookies} from 'next/headers'
import { dir } from 'i18next'
import { languages } from '../i18n/settings'

export async function generateStaticParams() {
    return languages.map((lng) => ({ lng }))
}

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
    params
}) {
    const { lng } = await params
    const cookieStore = await cookies()
    const supabase = await createClient(cookieStore)
    const {data: {user}} = await supabase.auth.getUser()

    return (
        <html lang={lng} dir={dir(lng)}>
        <body
            className={`antialiased`}
        >
        <>
            <Header user={user}/>
            {/*{logoutMessage && (*/}
            {/*    <div className="bg-green-500 text-white text-center py-3 fixed top-0 left-0 right-0 z-50">*/}
            {/*        {logoutMessage}*/}
            {/*    </div>*/}
            {/*)}*/}
            <main className="container mx-auto p-4 mt-12">{children}</main>
        </>
        </body>
        </html>
    );
}
